name: train_booking_app
version: 1.0.0+1
description: Indian Railways ticket booking app (IRCTC integration)
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.0.0
  flutter_svg: ^2.0.0
  # riverpod: ^2.0.0
  flutter_secure_storage: ^8.0.0
  # firebase_core: ^2.0.0
  # firebase_messaging: ^14.0.0
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.0
  provider: ^6.0.0
  url_launcher: ^6.0.0
  shared_preferences: ^2.5.3
  flutter_neumorphic_plus: 3.4.0
  uuid: ^4.5.1
  # lato: ^3.0.0
  # Add other dependencies as needed
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
