name: train_booking_app
version: 1.0.0+1
description: Indian Railways ticket booking app (IRCTC integration)
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  country_picker: ^2.0.20
  cupertino_icons: ^1.0.2
  dio: ^5.0.0
  flutter_svg: ^2.0.0
  # riverpod: ^2.0.0
  flutter_secure_storage: ^8.0.0
  # firebase_core: ^2.0.0
  # firebase_messaging: ^14.0.0
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.0
  provider: ^6.0.0
  url_launcher: ^6.0.0
  shared_preferences: ^2.5.3
  flutter_neumorphic_plus: 3.4.0
  uuid: ^4.5.1
  # lato: ^3.0.0
  marquee: ^2.2.3
  barcode_widget: ^2.0.4
  google_sign_in: ^6.1.5
  # Add other dependencies as needed

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/fonts/
    - assets/logos/

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/ProductSans-Italic.ttf
          style: italic
        - asset: assets/fonts/ProductSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/ProductSans-Light.ttf
          weight: 300
        - asset: assets/fonts/ProductSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/ProductSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/ProductSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/ProductSans-Black.ttf
          weight: 900
        - asset: assets/fonts/ProductSans-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/ProductSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/ProductSans-ThinItalic.ttf
          weight: 100
          style: italic
    - family: NotoColorEmoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji-Regular.ttf
