// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxBDunIyTmmnV3GtlgQr0YLOeATHDFfbw',
    appId: '1:649375767812:web:529fd14fc133fe61ad4451',
    messagingSenderId: '649375767812',
    projectId: 'tatkalpro-14fdd',
    authDomain: 'tatkalpro-14fdd.firebaseapp.com',
    storageBucket: 'tatkalpro-14fdd.firebasestorage.app',
    measurementId: 'G-HJ2Q36HNBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEhpQCZri5FitW5jvrplfLcp5T1C2Hbg8',
    appId: '1:649375767812:android:d8a2602f8f8ad562ad4451',
    messagingSenderId: '649375767812',
    projectId: 'tatkalpro-14fdd',
    storageBucket: 'tatkalpro-14fdd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZVQYjCnrQUsbVH46s7dliBkrCohytFtk',
    appId: '1:649375767812:ios:ed892ff17074ebf9ad4451',
    messagingSenderId: '649375767812',
    projectId: 'tatkalpro-14fdd',
    storageBucket: 'tatkalpro-14fdd.firebasestorage.app',
    iosBundleId: 'com.example.trainBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZVQYjCnrQUsbVH46s7dliBkrCohytFtk',
    appId: '1:649375767812:ios:ed892ff17074ebf9ad4451',
    messagingSenderId: '649375767812',
    projectId: 'tatkalpro-14fdd',
    storageBucket: 'tatkalpro-14fdd.firebasestorage.app',
    iosBundleId: 'com.example.trainBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxBDunIyTmmnV3GtlgQr0YLOeATHDFfbw',
    appId: '1:649375767812:web:bb8c735bbcf3a90bad4451',
    messagingSenderId: '649375767812',
    projectId: 'tatkalpro-14fdd',
    authDomain: 'tatkalpro-14fdd.firebaseapp.com',
    storageBucket: 'tatkalpro-14fdd.firebasestorage.app',
    measurementId: 'G-DRQY1VNHD6',
  );
}
