name: Deploy Lambda

on:
  workflow_dispatch:
  push:
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies for Lambda (Amazon Linux 2)
      run: |
        cd backend
        docker run --rm -v "$PWD":/var/task public.ecr.aws/sam/build-python3.11 pip install -r requirements.txt -t .

    - name: Zip Lambda code
      run: |
        cd backend
        zip -r lambda.zip . -x '*.pyc' '*.pyo' '*__pycache__*' 'venv/*' 'terraform/*'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Upload Lambda code to S3 and update Lambda
      run: |
        # Create a unique S3 object key with timestamp
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        S3_KEY="lambda-deployments/tatkalpro-backend-$TIMESTAMP.zip"
        
        # Upload the zip to S3
        aws s3 cp backend/lambda.zip s3://${{ secrets.LAMBDA_DEPLOYMENT_BUCKET }}/$S3_KEY
        
        # Update the Lambda function code from S3
        aws lambda update-function-code \
          --function-name tatkalpro-backend \
          --s3-bucket ${{ secrets.LAMBDA_DEPLOYMENT_BUCKET }} \
          --s3-key $S3_KEY \
          --region ap-south-1
