name: Deploy Lambda

on:
  push:
    paths:
      - 'backend/lambda_function/**'
      - 'backend/terraform/**'
      - '.github/workflows/deploy-lambda.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies and zip Lambda
      run: |
        cd backend
        pip install -r requirements.txt -t .
        zip -r lambda.zip . -x '*.pyc' '*.pyo' '*__pycache__*' 'venv/*' 'terraform/*'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Upload Lambda code to AWS
      run: |
        aws lambda update-function-code \
          --function-name tatkalpro-backend \
          --zip-file fileb://backend/lambda.zip \
          --region ap-south-1
