name: Destroy Mock JSON Server

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type YES to confirm destroy of mock JSON resources'
        required: true
        default: 'NO'

jobs:
  destroy-mockjson:
    if: ${{ github.event.inputs.confirm == 'YES' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform-mockjson
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION || 'ap-south-1' }}
