name: Destroy Mock JSON Server

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type YES to confirm destroy of mock JSON resources'
        required: true
        default: 'NO'

jobs:
  destroy-mockjson:
    if: ${{ github.event.inputs.confirm == 'YES' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform-mockjson
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Print Time and Env
        run: |
          echo "Current UTC time: $(date -u)"
          env
      - name: List Lambda Functions
        run: aws lambda list-functions
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION || 'ap-south-1' }}
      - name: List API Gateways
        run: aws apigateway get-rest-apis
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION || 'ap-south-1' }}
      - name: List ACM Certificates
        run: aws acm list-certificates
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION || 'ap-south-1' }}
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan (before destroy)
        run: terraform plan -destroy -var="json_acm_certificate_arn=${{ secrets.JSON_ACM_CERTIFICATE_ARN }}"
      - name: Terraform Destroy with Debug Logging
        run: |
          export TF_LOG=DEBUG
          export TF_LOG_PATH=terraform-debug.log
          terraform destroy -auto-approve -var="json_acm_certificate_arn=${{ secrets.JSON_ACM_CERTIFICATE_ARN }}"
          echo "==== TF_LOG output ===="
          cat terraform-debug.log || true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION || 'ap-south-1' }}
