name: Terraform Apply (Infra Provision)

on:
  workflow_dispatch:

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init & Apply
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve \
            -var="acm_certificate_arn=arn:aws:acm:us-east-1:754355039501:certificate/8282b579-8c01-474f-a023-4ddd2fb1c060"
        env:
          TF_VAR_aws_region: ap-south-1
          TF_VAR_custom_domain: services.tatkalpro.in
